import JSZip from 'jszip';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface PackOptions {
  posterUrl?: string;       // Feed 1:1 image URL
  storyCardUrl?: string;    // Story 9:16 image URL
  captions: {
    instagram?: string;
    facebook?: string;
    tiktok?: string;
    google?: string;
    sms?: string;
  };
  barName?: string;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Fetch an image from a URL and return its buffer.
 * Returns null if the fetch fails (graceful degradation).
 */
async function fetchImageBuffer(url: string): Promise<Buffer | null> {
  try {
    const res = await fetch(url, { cache: 'no-store' });
    if (!res.ok) return null;
    const arrayBuffer = await res.arrayBuffer();
    return Buffer.from(arrayBuffer);
  } catch {
    return null;
  }
}

/**
 * Derive a safe filename extension from a URL.
 */
function extensionFromUrl(url: string): string {
  try {
    const pathname = new URL(url).pathname;
    const ext = pathname.split('.').pop()?.toLowerCase();
    if (ext && ['jpg', 'jpeg', 'png', 'webp', 'gif'].includes(ext)) {
      return ext === 'jpeg' ? 'jpg' : ext;
    }
  } catch {
    // ignore
  }
  return 'png'; // sensible default for AI-generated images
}

// ─── README Content ───────────────────────────────────────────────────────────

function buildReadme(options: PackOptions): string {
  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `TAPPOST — CONTENT PACK
${'='.repeat(40)}
Bar: ${options.barName ?? 'Your Bar'}
Generated: ${date}

FOLDER STRUCTURE
${'─'.repeat(40)}
/Instagram_Feed/     — 1:1 poster image + Instagram caption
/Instagram_Story/    — 9:16 story card image + story caption
/Facebook/           — poster image + Facebook caption
/TikTok/             — poster image + TikTok caption
/Other/              — Google Business + SMS captions

HOW TO USE
${'─'.repeat(40)}
1. Each folder contains a ready-to-post image and caption file.
2. The .txt files contain your AI-generated captions — edit before posting.
3. All captions include any edits you made in the TapPost editor.

Generated by TapPost — tappost.io
`;
}

// ─── Main ZIP Builder ─────────────────────────────────────────────────────────

/**
 * Builds a ZIP buffer with platform folders.
 * Structure:
 *   /Instagram_Feed/   — poster + instagram caption
 *   /Instagram_Story/  — story card + story/instagram caption
 *   /Facebook/         — poster + facebook caption
 *   /TikTok/           — poster + tiktok caption
 *   /Other/            — google + sms captions (text only, no image)
 *   README.txt
 */
export async function buildDownloadPack(options: PackOptions): Promise<Buffer> {
  const zip = new JSZip();

  // Fetch images concurrently (if URLs provided)
  const [posterBuffer, storyBuffer] = await Promise.all([
    options.posterUrl ? fetchImageBuffer(options.posterUrl) : Promise.resolve(null),
    options.storyCardUrl ? fetchImageBuffer(options.storyCardUrl) : Promise.resolve(null),
  ]);

  const posterExt = options.posterUrl ? extensionFromUrl(options.posterUrl) : 'png';
  const storyExt = options.storyCardUrl ? extensionFromUrl(options.storyCardUrl) : 'png';

  // ── Instagram Feed Folder ──────────────────────────────────────────────────
  const igFeed = zip.folder('Instagram_Feed')!;
  if (posterBuffer) {
    igFeed.file(`poster.${posterExt}`, posterBuffer);
  }
  if (options.captions.instagram) {
    igFeed.file('caption.txt', options.captions.instagram);
  }

  // ── Instagram Story Folder ────────────────────────────────────────────────
  const igStory = zip.folder('Instagram_Story')!;
  if (storyBuffer) {
    igStory.file(`story.${storyExt}`, storyBuffer);
  }
  // Story caption = instagram caption (same brand voice)
  if (options.captions.instagram) {
    igStory.file('caption.txt', options.captions.instagram);
  }

  // ── Facebook Folder ───────────────────────────────────────────────────────
  const fb = zip.folder('Facebook')!;
  if (posterBuffer) {
    fb.file(`poster.${posterExt}`, posterBuffer);
  }
  if (options.captions.facebook) {
    fb.file('caption.txt', options.captions.facebook);
  }

  // ── TikTok Folder ─────────────────────────────────────────────────────────
  const tt = zip.folder('TikTok')!;
  if (posterBuffer) {
    tt.file(`poster.${posterExt}`, posterBuffer);
  }
  if (options.captions.tiktok) {
    tt.file('caption.txt', options.captions.tiktok);
  }

  // ── Other Folder (Google + SMS) ───────────────────────────────────────────
  const other = zip.folder('Other')!;
  if (options.captions.google) {
    other.file('google_business_caption.txt', options.captions.google);
  }
  if (options.captions.sms) {
    other.file('sms_message.txt', options.captions.sms);
  }

  // ── README ────────────────────────────────────────────────────────────────
  zip.file('README.txt', buildReadme(options));

  // Generate ZIP as a Node.js Buffer (server-side use)
  const zipBuffer = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  return zipBuffer;
}
